#--------------------------------------------------------------------
#    The MB-system:  mbjl_histplot_script.jl
#
#    Copyright (c) 2026 by
#    David W. Caress (caress@mbari.org)
#      Monterey Bay Aquarium Research Institute
#      Moss Landing, California, USA
#
#    See README.md file for copying and redistribution conditions.
#--------------------------------------------------------------------
#
# Purpose:
#   Julia port of src/macros/python/mbpy_histplot_script.py, itself a
#   port of mbm_histplot's page-layout and script-generation
#   logic, targeting GMT **modern mode** (`gmt begin`/`gmt end`,
#   `gmt histogram` -- the modern-mode name for classic `pshistogram`,
#   confirmed to be the same module by identical --help banners)
#   instead of mbm_histplot's own classic-mode <root>.cmd generator.
#
#   mbm_histplot is a much simpler macro than mbm_grdplot/mbm_grd3dplot:
#   it plots a one-column data *file* (not a grid) as a frequency
#   histogram. It shares the same page-size/width/height/font *tables*
#   and GetProjection (confirmed identical to mbm_grdplot's copy by
#   direct diff, module scaffolding aside) -- reused here from
#   mbjl_layout.jl. Its GetPageSize, however, is NOT the same sub
#   despite using the same tables (see get_page_size_hist() below), and
#   neither is its default-scale auto-fit algorithm (see
#   compute_layout_hist()'s own docstring) -- both were wrongly assumed
#   reusable from mbpy_layout/mbpy_grdplot_script in an earlier version
#   of the Python port, which silently produced a squashed, barely-legible
#   plot until caught against real mbm_trnplot output. What is unique
#   to mbm_histplot:
#
#     - it pre-scans the input file itself (mbm_histplot lines ~270-359)
#       to determine the plot's x bounds (data min/max, or the -R
#       override) and, unless -R gave an explicit y range too, bins the
#       data itself with the *same* cell width GMT's own `histogram`
#       will use, purely to compute a y-axis (frequency %) upper bound
#       with a 10% margin. The actual bars in the final plot are drawn
#       by `gmt histogram` re-reading and re-binning the raw file
#       itself (mbm_histplot never passes its own bin counts to GMT) --
#       this port does the same two-pass thing, not because GMT could
#       not bin the data cheaper, but because the pre-scan is also
#       exactly how the plot's y-range is chosen at all.
#     - its own GetBaseTickLinear (mbm_histplot lines ~1574-1606): a
#       "nice number" tick heuristic distinct from mbjl_layout's
#       (rounds to (10**n)/5 with a /4 or /2 refinement, vs.
#       mbjl_layout's (10**n)/10 with the same /4-or-/2 shape) used
#       whenever the projection is plain Cartesian ("x"/"X", not the
#       special "xd"/"Xd" -- see get_base_tick_geo() below); its
#       GetBaseTick (mbm_histplot lines ~1608-1695) is the same
#       geographic degree/minute/second table MbjlLayout.get_base_tick
#       already has, just with tick = min(dx, dy)/5 instead of /3 --
#       used only for the "xd"/"Xd" or a real geographic -J.
#     - a fixed, always-on mean/+-1 sigma/+-2 sigma normal-curve overlay
#       (`-N0+pblack -N1+pred -N2+pgreen`, mbm_histplot line ~910) with
#       no option to disable it -- reproduced as unconditional here too.
#
#   NOTE on real, confirmed-dead pieces of mbm_histplot itself: several
#   variables read out in the script-header/verbose-summary code ($cptfile,
#   $file_cpt, $data_scale, @xyfiles, $save_temp_files, $unix_stamp/
#   $unix_stamp_on) are never assigned anywhere in the source -- no -M
#   sub-option or top-level flag sets any of them (mbm_histplot's -M only
#   dispatches -MIE/-MIT, unlike mbm_grdplot/mbm_grd3dplot's much larger
#   -M grammar). These read as leftover copy-paste from the mbm_grdplot
#   template mbm_histplot was originally cloned from. This port does not
#   expose --data-scale, --xy-overlay, --unix-stamp, or any CPT-file
#   option, since none of that is real, reachable functionality in the
#   macro being ported.
#
# Status:
#   Covers the full documented option set (cell width, fill, pen,
#   title/x-label/y-label, tick-info override, region, projection/page
#   sizing). Verified by running the generated script through a real
#   GMT 6 installation; not exhaustively line-by-line diffed against
#   Perl output the way mbjl_grdplot_script.jl was. The generated
#   scripts were diffed against the Python port's (mbpy_histplot) own
#   output and match it byte for byte apart from the "Generated by" line.
#
isdefined(@__MODULE__, :MbjlUtil) || include(joinpath(@__DIR__, "mbjl_util.jl"))
isdefined(@__MODULE__, :MbjlLayout) || include(joinpath(@__DIR__, "mbjl_layout.jl"))
isdefined(@__MODULE__, :MbjlGrdplotScript) || include(joinpath(@__DIR__, "mbjl_grdplot_script.jl"))

module MbjlHistplotScript

using ..MbjlUtil
using ..MbjlLayout
using ..MbjlGrdplotScript: baseline_gmt_defaults

export scan_data_bounds, compute_histogram_yrange, get_base_tick_linear,
       get_page_size_hist, get_base_tick_geo, LayoutHist, compute_layout_hist,
       ScriptOptionsHist, generate_script_hist, generate_and_write_hist

const _DTR = 3.1415926 / 180.0


"""Port of mbm_histplot's first data-file pass (lines ~270-288):
find the data's own min/max and count. Values are read one per
line, exactly as the Perl `while (\$data=<F>)` loop does (leading/
trailing whitespace and blank lines are skipped)."""
function scan_data_bounds(file_path::AbstractString)::Tuple{Float64,Float64,Int}
    xmin = xmax = nothing
    count = 0
    open(file_path) do f
        for line in eachline(f)
            s = strip(line)
            if isempty(s)
                continue
            end
            v = pyfloat(split(s)[1])
            if xmin === nothing || v < xmin
                xmin = v
            end
            if xmax === nothing || v > xmax
                xmax = v
            end
            count += 1
        end
    end
    if count <= 0
        error("Input file $file_path appears to contain no data.")
    end
    return xmin, xmax, count
end


"""Port of the second data-file pass (lines ~332-359): bin the data
at `cellwidth` starting at `xmin`, convert counts to percent of
total, and return 1.1x the largest bin's percentage (or 50.0 if
every bin is empty) -- mirrors mbm_histplot's own y-axis margin.
Bin index `i` is 0-based, as in the Python original."""
function compute_histogram_yrange(file_path::AbstractString, xmin::Real, cellwidth::Real,
                                  ncell::Integer, count::Integer)::Float64
    cellcount = zeros(Int, ncell)
    open(file_path) do f
        for line in eachline(f)
            s = strip(line)
            if isempty(s)
                continue
            end
            v = pyfloat(split(s)[1])
            i = floor(Int, (v - xmin) / cellwidth)
            if 0 <= i < ncell
                cellcount[i+1] += 1
            end
        end
    end
    ymax = 0.0
    for c in cellcount
        pct = 100.0 * c / count
        if pct > ymax
            ymax = pct
        end
    end
    return ymax <= 0.0 ? 50.0 : 1.1 * ymax
end


"""Port of mbm_histplot's own GetBaseTickLinear (lines ~1574-1606):
a "nice number" tick heuristic distinct from mbjl_layout's own
get_base_tick() -- (10**n)/5 rather than (10**n)/10, with the same
/4-or-/2 refinement shape."""
function get_base_tick_linear(xmin::Real, xmax::Real, ymin::Real, ymax::Real)::Tuple{Float64,Float64}
    function one(d)
        if d <= 0
            return 0.0
        end
        base = pytrunc((log(d) / log(10.0)) + 0.5)
        tick = (10.0^base) / 5.0
        if d / tick < 5
            tick = tick / 4.0
        elseif d / tick < 10
            tick = tick / 2.0
        end
        return tick
    end

    return one(xmax - xmin), one(ymax - ymin)
end


"""Port of mbm_histplot's own GetPageSize (a completely different
sub from MbjlLayout.get_page_size(), despite sharing the same page-
size/width/height tables) -- confirmed by direct comparison: unlike
mbm_grdplot's version, it has no scale_loc-dependent branching at
all (a single fixed margin proportion regardless of a color scale's
placement -- appropriate since a histogram has no color scale bar to
make room for) and, more consequentially, no clamping of the margins
to an absolute maximum -- mbm_grdplot's version clamps e.g.
space_top to min(1.5*ratio, 4.5), while this one lets every margin
scale unbounded with page size. Confirmed directly: reusing
MbjlLayout.get_page_size() here silently produced a ~13% smaller
height_max_landscape than the real macro for page size "a" (5.0 vs.
the real 5.75), which was large enough to visibly distort the
default-scale computation in compute_layout_hist()."""
function get_page_size_hist(pagesize::AbstractString)::PageMargins
    page_h = PAGE_HEIGHT_IN[pagesize]
    page_w = PAGE_WIDTH_IN[pagesize]
    a_h = PAGE_HEIGHT_IN["a"]
    ratio = page_h / a_h

    space_top = 1.25 * ratio
    space_bottom = 1.50 * ratio
    space_left = 1.00 * ratio
    space_right = 1.00 * ratio

    return PageMargins(
        space_top = space_top, space_bottom = space_bottom,
        space_left = space_left, space_right = space_right,
        width_max_landscape = page_h - space_left - space_right,
        height_max_landscape = page_w - space_bottom - space_top,
        width_max_portrait = page_w - space_left - space_right,
        height_max_portrait = page_h - space_bottom - space_top,
    )
end


"""Port of mbm_histplot's own GetBaseTick (lines ~1608-1695): the
same geographic degree/minute/second lookup table MbjlLayout.
get_base_tick() uses, but with tick = min(dx, dy)/5 rather than /3.
Used only for a real geographic -J or the special "xd"/"Xd" flag
(mbjl_grd3dplot/mbjl_layout call this "linear"; mbm_histplot itself
confusingly calls it "geographic" -- same meaning, see this
module's own top docstring)."""
function get_base_tick_geo(xmin::Real, xmax::Real, ymin::Real, ymax::Real)::String
    base_tick = min((xmax - xmin) / 5.0, (ymax - ymin) / 5.0)
    tick_str = "60"
    for (threshold, label) in MbjlLayout._GEOGRAPHIC_TICK_TABLE
        if base_tick < threshold
            tick_str = label
            break
        end
    end
    return tick_str
end


Base.@kwdef mutable struct LayoutHist
    pagesize::String
    projection::String
    projection_pars::String
    region::String
    xoffset::Float64
    yoffset::Float64
    axes_interval::String   # the "-Bx...+l... -By...+l..." or "-B<tick>" piece
end


_truthy(x) = x !== nothing && x != 0

"""Port of mbm_histplot's page/scale-fit algorithm (lines ~369-738):
the same GetPageSize/GetProjection heuristics mbjl_layout uses
(default projection "x", plain linear/Cartesian, unlike mbm_grdplot's
default Mercator), applied to the histogram's own x/y (value/
frequency-percent) bounding box instead of a grid's geographic
bounds.
"""
function compute_layout_hist(
    xmin::Real, xmax::Real, ymin::Real, ymax::Real;
    pagesize::AbstractString = "a",
    map_scale::Union{Nothing,AbstractString} = nothing,
    orientation::Integer = 0,
    xlabel::AbstractString = " ",
    ylabel::AbstractString = "Frequency %",
    tick_info::Union{Nothing,AbstractString} = nothing,
)::LayoutHist
    pagesize = String(pagesize)
    map_scale = (map_scale === nothing || isempty(map_scale)) ? nothing : String(map_scale)
    margins = get_page_size_hist(pagesize)

    use_scale = use_width = use_ratio = linear = false
    separator = ""
    trial_value = "1.0"
    plot_scale = plot_width = nothing
    projection = projection_pars = nothing

    if map_scale !== nothing
        spec = get_projection(map_scale)
        projection = spec.projection
        projection_pars = spec.projection_pars
        use_scale, use_width = spec.use_scale, spec.use_width
        use_ratio, linear = spec.use_ratio, spec.linear
        separator, trial_value = spec.separator, spec.trial_value
        plot_scale, plot_width = spec.plot_scale, spec.plot_width

        # This trial-value append (for the mapproject probe just below)
        # only applies to a partially-parsed *user* map_scale (e.g. a
        # bare "-Jx" with no number, where get_projection() leaves
        # projection_pars as just the projection letter's remainder).
        # It must not run for the "no map_scale given" default below,
        # whose own "1/1" is already a complete, valid probe value --
        # appending trial_value to *that* produced a nonsensical
        # "1/11.0" (confirmed the cause of a garbled probe scale).
        if (use_scale && _truthy(plot_scale)) || (use_width && _truthy(plot_width))
            # nothing
        elseif use_scale || use_width
            projection_pars = "$(projection_pars)$(separator)$(trial_value)"
        end
    else
        projection, projection_pars = "x", "1/1"
        use_scale = true
    end

    bounds_plot = "$(fmtg(xmin, 8))/$(fmtg(xmax, 8))/$(fmtg(ymin, 8))/$(fmtg(ymax, 8))"
    dxx, dyy = MbjlLayout._mapproject_bbox(xmin, xmax, ymin, ymax, projection, projection_pars, bounds_plot)
    dxx, dyy = abs(dxx), abs(dyy)

    landscape = portrait = false
    width = height = 0.0
    width_max = height_max = 0.0

    if (use_scale && _truthy(plot_scale)) || (use_width && _truthy(plot_width))
        plot_width_, plot_height_ = dxx, dyy
        if orientation == 1
            portrait = true
            width, height = PAGE_WIDTH_IN[pagesize], PAGE_HEIGHT_IN[pagesize]
            width_max, height_max = margins.width_max_portrait, margins.height_max_portrait
        elseif orientation == 2
            landscape = true
            width, height = PAGE_HEIGHT_IN[pagesize], PAGE_WIDTH_IN[pagesize]
            width_max, height_max = margins.width_max_landscape, margins.height_max_landscape
        elseif dxx > dyy
            landscape = true
            width, height = PAGE_HEIGHT_IN[pagesize], PAGE_WIDTH_IN[pagesize]
            width_max, height_max = margins.width_max_landscape, margins.height_max_landscape
        else
            portrait = true
            width, height = PAGE_WIDTH_IN[pagesize], PAGE_HEIGHT_IN[pagesize]
            width_max, height_max = margins.width_max_portrait, margins.height_max_portrait
        end

        if plot_width_ > width_max || plot_height_ > height_max
            good_page = nothing
            for elem in PAGE_SIZE_NAMES
                m2 = get_page_size_hist(elem)
                wm = portrait ? m2.width_max_portrait : m2.width_max_landscape
                hm = portrait ? m2.height_max_portrait : m2.height_max_landscape
                if plot_width_ <= wm && plot_height_ <= hm
                    good_page = elem
                    break
                end
            end
            if good_page === nothing
                good_page = pagesize
            end
            pagesize = good_page
            margins = get_page_size_hist(pagesize)
            width = portrait ? PAGE_WIDTH_IN[pagesize] : PAGE_HEIGHT_IN[pagesize]
            height = portrait ? PAGE_HEIGHT_IN[pagesize] : PAGE_WIDTH_IN[pagesize]
        end

        plot_width, plot_height = plot_width_, plot_height_

    elseif use_scale && projection == "x" && !linear
        # Port of mbm_histplot's own real default-scale branch (lines
        # ~526-567) -- NOT the same algorithm as mbm_grdplot/mbjl_layout's
        # uniform-scale auto-fit (which picks a single scale preserving
        # the data's own x/y aspect ratio, appropriate for a geographic
        # map). A histogram's x (data value) and y (frequency percent)
        # axes have unrelated units and usually wildly different natural
        # ranges, so mbm_histplot instead computes two *independent*
        # scales that each separately stretch to fill the page, and
        # (unlike mbm_grdplot) always defaults to landscape orientation
        # rather than picking whichever orientation yields a bigger
        # scale. Confirmed directly against real mbm_histplot output: a
        # first attempt at the Python port reused mbm_grdplot's uniform-scale
        # logic here, which -- for a real 1.4-units-wide by 29-percent-
        # tall histogram -- produced a single scale small enough to fit
        # the *y* range on the page, squashing the plot to a fraction of
        # an inch wide; the real macro's own -Jx<xscale>/<yscale> two-
        # value scale for the same data confirmed this fix.
        if orientation == 1
            portrait = true
            plot_scale_x = margins.width_max_portrait / dxx
            plot_scale_y = margins.height_max_portrait / dyy
            width, height = PAGE_WIDTH_IN[pagesize], PAGE_HEIGHT_IN[pagesize]
        else
            landscape = true
            plot_scale_x = margins.width_max_landscape / dxx
            plot_scale_y = margins.height_max_landscape / dyy
            width, height = PAGE_HEIGHT_IN[pagesize], PAGE_WIDTH_IN[pagesize]
        end

        plot_width = dxx * plot_scale_x
        plot_height = dyy * plot_scale_y
        projection_pars = "$(pystr(plot_scale_x))/$(pystr(plot_scale_y))"

    elseif use_width && projection == "X" && !linear
        # Port of mbm_histplot's own real default-width branch (lines
        # ~568-607): same independent-x/y-axis idea as the scale branch
        # above, but for an explicit total plot width (-JX<width>)
        # instead of an auto-computed scale.
        if orientation == 1
            portrait = true
            plot_width_x = margins.width_max_portrait
            plot_width_y = margins.height_max_portrait
            width, height = PAGE_WIDTH_IN[pagesize], PAGE_HEIGHT_IN[pagesize]
        else
            landscape = true
            plot_width_x = margins.width_max_landscape
            plot_width_y = margins.height_max_landscape
            width, height = PAGE_HEIGHT_IN[pagesize], PAGE_WIDTH_IN[pagesize]
        end

        plot_width, plot_height = plot_width_x, plot_width_y
        projection_pars = "$(pystr(plot_width_x))/$(pystr(plot_width_y))"

    elseif use_scale
        plot_scale_landscape = margins.width_max_landscape / dxx
        if plot_scale_landscape * dyy > margins.height_max_landscape
            plot_scale_landscape = margins.height_max_landscape / dyy
        end
        plot_scale_portrait = margins.width_max_portrait / dxx
        if plot_scale_portrait * dyy > margins.height_max_portrait
            plot_scale_portrait = margins.height_max_portrait / dyy
        end

        if orientation == 1
            portrait = true
            plot_scale = plot_scale_portrait
            width, height = PAGE_WIDTH_IN[pagesize], PAGE_HEIGHT_IN[pagesize]
        elseif orientation == 2
            landscape = true
            plot_scale = plot_scale_landscape
            width, height = PAGE_HEIGHT_IN[pagesize], PAGE_WIDTH_IN[pagesize]
        elseif plot_scale_landscape > plot_scale_portrait
            landscape = true
            plot_scale = plot_scale_landscape
            width, height = PAGE_HEIGHT_IN[pagesize], PAGE_WIDTH_IN[pagesize]
        else
            portrait = true
            plot_scale = plot_scale_portrait
            width, height = PAGE_WIDTH_IN[pagesize], PAGE_HEIGHT_IN[pagesize]
        end

        plot_width = dxx * plot_scale
        plot_height = dyy * plot_scale

        base = MbjlLayout._base_pars(projection, map_scale)
        if use_ratio
            top = pytrunc(1 / plot_scale)
            projection_pars = "$(base)$(separator)1:$(top)"
        else
            projection_pars = MbjlLayout._sprintf_g5(base, separator, plot_scale)
        end
        if linear
            projection_pars = "$(projection_pars)d"
        end

    elseif use_width
        plot_width_landscape = min(margins.height_max_landscape * dxx / dyy, margins.width_max_landscape)
        plot_width_portrait = min(margins.height_max_portrait * dxx / dyy, margins.width_max_portrait)

        if orientation == 1
            portrait = true
            plot_width = plot_width_portrait
        elseif orientation == 2
            landscape = true
            plot_width = plot_width_landscape
        elseif plot_width_landscape > plot_width_portrait
            landscape = true
            plot_width = plot_width_landscape
        else
            portrait = true
            plot_width = plot_width_portrait
        end

        plot_height = plot_width * dyy / dxx
        if landscape
            width, height = PAGE_HEIGHT_IN[pagesize], PAGE_WIDTH_IN[pagesize]
        else
            width, height = PAGE_WIDTH_IN[pagesize], PAGE_HEIGHT_IN[pagesize]
        end

        base = MbjlLayout._base_pars(projection, map_scale)
        projection_pars = MbjlLayout._sprintf_g5(base, separator, plot_width)
        if linear
            projection_pars = "$(projection_pars)d"
        end
    end

    xoffset = (width - abs(plot_width) - margins.space_left - margins.space_right) / 2 + margins.space_left
    yoffset = (height - abs(plot_height) - margins.space_bottom - margins.space_top) / 2 + margins.space_bottom

    if tick_info !== nothing && !isempty(tick_info)
        axes_interval = "-B$(tick_info)"
    elseif first(projection, 1) in ("x", "X") && !linear
        tick_x, tick_y = get_base_tick_linear(xmin, xmax, ymin, ymax)
        axes_interval = "-Bx$(fmtg(tick_x, 6))+l\"$(xlabel)\" -By$(fmtg(tick_y, 6))+l\"$(ylabel)\""
    else
        tick = get_base_tick_geo(xmin, xmax, ymin, ymax)
        axes_interval = "-B$(tick)"
    end

    return LayoutHist(
        pagesize = pagesize, projection = projection, projection_pars = projection_pars,
        region = bounds_plot, xoffset = xoffset, yoffset = yoffset, axes_interval = axes_interval,
    )
end


Base.@kwdef mutable struct ScriptOptionsHist
    file_data::String
    root::String
    layout::LayoutHist
    xmin::Float64                      # bin range for -T (mbm_histplot's own $xmin/$xmax,
    xmax::Float64                      # which may differ from the plot's x -R after cell-gridding)
    cellwidth::Float64                 # -MC's cell width -> -T<xmin>/<xmax>/<cellwidth>
    output_format::String = "pdf"
    title::Union{Nothing,String} = nothing
    dpi::Union{Nothing,Int} = nothing
    fill::Union{Nothing,String} = "gray"     # -G; "N" (or nothing) disables fill
    pen::Union{Nothing,String} = "1p"        # -L (histogram's own outline-pen flag)
    gmt_defs::Vector{String} = String[]
end


_nonempty(s) = s !== nothing && !isempty(s)

"""Python's str.partition(sep): (head, sep, tail)."""
function _partition(s::AbstractString, sep::AbstractString)
    r = findfirst(sep, s)
    r === nothing && return (String(s), "", "")
    return (String(s[1:prevind(s, first(r))]), String(sep), String(s[nextind(s, last(r)):end]))
end


"""Build the full GMT modern-mode shellscript text for `opts`.
Does not touch the filesystem at all (unlike the grdplot/grd3dplot
generators, there is no CPT file to write for a histogram plot)."""
function generate_script_hist(opts::ScriptOptionsHist)::String
    lay = opts.layout
    j = "-J$(lay.projection)$(lay.projection_pars)"
    r = "-R$(lay.region)"

    lines = String[
        "#!/usr/bin/env bash",
        "#",
        "# GMT modern-mode histogram plotting script for $(opts.file_data)",
        "# Generated by mbjl_histplot_script.jl (Julia port of mbm_histplot)",
        "#",
        "set -e",
        "",
        "gmt begin $(opts.root) $(opts.output_format)",
        "",
    ]

    if opts.dpi !== nothing && opts.dpi != 0
        push!(lines, "gmt figure $(opts.root) $(opts.output_format) E$(opts.dpi)")
        push!(lines, "")
    end

    push!(lines, "# Set temporary GMT defaults")
    baseline_pairs = String[]
    for gmt_def in baseline_gmt_defaults(lay.pagesize, false, "ddd:mm")
        param, _, value = _partition(gmt_def, " ")
        push!(baseline_pairs, "$param $value")
    end
    push!(lines, "gmt set $(join(baseline_pairs, " "))")
    push!(lines, "")

    if !isempty(opts.gmt_defs)
        push!(lines, "# User-defined GMT parameter overrides")
        user_pairs = String[]
        for gmt_def in opts.gmt_defs
            param, _, value = _partition(gmt_def, "/")
            push!(user_pairs, "$param $value")
        end
        push!(lines, "gmt set $(join(user_pairs, " "))")
        push!(lines, "")
    end

    title = opts.title !== nothing ? opts.title : "Frequency Histogram of $(opts.file_data)"
    axes = "-BWESN" * (_nonempty(title) ? "+t\"$(title)\"" : "") * " $(lay.axes_interval)"

    hparts = String["gmt histogram $(opts.file_data) $j $r", axes,
                    "-T$(fmtg(opts.xmin, 8))/$(fmtg(opts.xmax, 8))/$(fmtg(opts.cellwidth, 8))", "-Z1"]
    if _nonempty(opts.pen)
        # NOTE: classic pshistogram's outline-pen flag was -L; current
        # GMT's `histogram` module (confirmed via its own --help) has no
        # -L at all and uses -W instead, like nearly every other GMT
        # plotting module's pen option. mbm_histplot's Perl source still
        # emits classic -L$pen, which is simply not a valid flag for a
        # current `gmt histogram`/`pshistogram` -- this is not a classic-
        # vs-modern-*mode* difference (unlike gmtset/set) but a genuine
        # GMT module syntax change over time, ported to current syntax.
        push!(hparts, "-W$(opts.pen)")
    end
    if _nonempty(opts.fill) && opts.fill != "N"
        push!(hparts, "-G$(opts.fill)")
    end
    push!(hparts, "-N0+pblack -N1+pred -N2+pgreen")
    push!(lines, join(hparts, " "))
    push!(lines, "")

    push!(lines, "gmt end")
    push!(lines, "")
    return join(lines, "\n")
end


function generate_and_write_hist(opts::ScriptOptionsHist, script_path::AbstractString)
    write(script_path, generate_script_hist(opts))
    chmod(script_path, 0o755)
    return nothing
end

end # module MbjlHistplotScript
